jobs:
  deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::135808920063:role/github
      - run: terraform init
      - run: terraform apply -auto-approve
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
